spring.application.name=administraArchivos

# Puerto
server.port=8081

# Conexion_MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/adminarchivos
spring.datasource.username=root
spring.datasource.password=cebero1593

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Para respetar los nombres en la base de datos
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#ruta para los archivos a subir
ruta.archivos=C:/archivos_app_prueba

#tamaño maxio para archivos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
